plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.14.7'
    id 'maven-publish'
}

ext.profile_id = 'mc1_21_10'
ext.source_profile_id = 'mc1_21_9_to_1_21_10'
ext.profile_suffix = 'mc1.21.10'
ext.minecraft_version = '1.21.10'
ext.minecraft_min_version = '1.21.10'
ext.minecraft_max_version = '1.21.10'
ext.loader_version = '0.19.5'
ext.fabric_version = '0.138.4+1.21.10'
ext.modmenu_version = '16.0.1'
ext.java_version = 21
ext.runtime_java_version = 25
apply from: 'gradle/profile-1.21.gradle'
